# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate combine

Name:           rust-%{crate}
Version:        3.8.1
Release:        1%{?dist}
Summary:        Fast parser combinators on arbitrary streams with zero-copy support

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/combine
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Fast parser combinators on arbitrary streams with zero-copy support.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+combine-regex-1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+combine-regex-1-devel %{_description}

This package contains library source intended for building other packages
which use "combine-regex-1" feature of "%{crate}" crate.

%files       -n %{name}+combine-regex-1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+doc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+doc-devel %{_description}

This package contains library source intended for building other packages
which use "doc" feature of "%{crate}" crate.

%files       -n %{name}+doc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mp4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp4-devel %{_description}

This package contains library source intended for building other packages
which use "mp4" feature of "%{crate}" crate.

%files       -n %{name}+mp4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages
which use "regex" feature of "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+regex-1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-1-devel %{_description}

This package contains library source intended for building other packages
which use "regex-1" feature of "%{crate}" crate.

%files       -n %{name}+regex-1-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 22 19:14:53 CEST 2020 pluth <pluth@0t.re> - 3.8.1-1
- Initial package
