# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate combine

Name:           rust-%{crate}
Version:        4.3.2
Release:        1%{?dist}
Summary:        Fast parser combinators on arbitrary streams with zero-copy support

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/combine
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Fast parser combinators on arbitrary streams with zero-copy support.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bytes_05-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytes_05-devel %{_description}

This package contains library source intended for building other packages
which use "bytes_05" feature of "%{crate}" crate.

%files       -n %{name}+bytes_05-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-03-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-03-devel %{_description}

This package contains library source intended for building other packages
which use "futures-03" feature of "%{crate}" crate.

%files       -n %{name}+futures-03-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-io-03-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-io-03-devel %{_description}

This package contains library source intended for building other packages
which use "futures-io-03" feature of "%{crate}" crate.

%files       -n %{name}+futures-io-03-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-util-03-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-util-03-devel %{_description}

This package contains library source intended for building other packages
which use "futures-util-03" feature of "%{crate}" crate.

%files       -n %{name}+futures-util-03-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mp4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp4-devel %{_description}

This package contains library source intended for building other packages
which use "mp4" feature of "%{crate}" crate.

%files       -n %{name}+mp4-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pin-project-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pin-project-devel %{_description}

This package contains library source intended for building other packages
which use "pin-project" feature of "%{crate}" crate.

%files       -n %{name}+pin-project-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pin-project-lite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pin-project-lite-devel %{_description}

This package contains library source intended for building other packages
which use "pin-project-lite" feature of "%{crate}" crate.

%files       -n %{name}+pin-project-lite-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages
which use "regex" feature of "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-02-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-02-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-02" feature of "%{crate}" crate.

%files       -n %{name}+tokio-02-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-02-dep-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-02-dep-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-02-dep" feature of "%{crate}" crate.

%files       -n %{name}+tokio-02-dep-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Sep 22 18:21:00 CEST 2020 kai - 4.3.2-1
- Initial package
